use whatever --resconf=<file> is given, even if the file isn't readable

diff --git a/support/configure b/support/configure
--- a/support/configure
+++ b/support/configure
@@ -3768,41 +3768,30 @@ echo "configure:3768: checking for resolver configuration file" >&5
 if eval "test \"`echo '$''{'irc_cv_path_resconf'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-  no_resconf=yes
-for irc_file in `test -z "$irc_resconf" || echo "$irc_resconf"` \
-                /etc/resolv.conf; \
-  do
-    if test -r "$irc_file"; then
-      no_resconf=
-      irc_cv_path_resconf="$irc_file"
-      break
-    fi
-  done
+  if test -z "$irc_resconf"; then
+   irc_cv_path_resconf="/etc/resolv.conf";
+ else
+   irc_cv_path_resconf="$irc_resconf";
+ fi
 
 fi
 
-if test "$no_resconf" = yes; then
-  echo "$ac_t""not found... falling back on default (/etc/resolv.conf)" 1>&6
-  echo "configure: warning: without resolver configuration file, the server won't work." 1>&2
-  cat >> confdefs.h <<\EOF
-#define IRC_RESCONF "/etc/resolv.conf"
-EOF
-
-else
-  echo "$ac_t""$irc_cv_path_resconf" 1>&6
-  cat >> confdefs.h <<EOF
+echo "$ac_t""$irc_cv_path_resconf" 1>&6
+cat >> confdefs.h <<EOF
 #define IRC_RESCONF "$irc_cv_path_resconf"
 EOF
 
+if test ! -r "$irc_cv_path_resconf"; then
+  echo "configure: warning: Unable to read \"$irc_cv_path_resconf\"! Without resolver configuration file, the server won't work." 1>&2
 fi
 
 echo $ac_n "checking whether this is an alpha/beta release""... $ac_c" 1>&6
-echo "configure:3801: checking whether this is an alpha/beta release" >&5
+echo "configure:3790: checking whether this is an alpha/beta release" >&5
 if eval "test \"`echo '$''{'irc_cv_alpha_beta'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3806 "configure"
+#line 3795 "configure"
 #include "confdefs.h"
 #include "../common/patchlevel.h"
 #ifdef PATCHLEVEL
